// CNC Tool Database
// Sourced from Rick's documentation in /tmp/cnc/
// All dimensions in inches unless otherwise noted

const TOOL_DATABASE = [
  {
    id: "amana-46202-k",
    name: "Amana 46202-K",
    partNumber: "46202-K",
    flutes: 2,
    direction: "Down",
    type: "Spiral Plunge",
    diameter: 0.25,
    diameterStr: "1/4\"",
    angle: null,
    radius: null,
    cuttingHeight: 0.75,
    shank: 0.25,
    overallLength: 2.5,
    chipLoadMin: 0.005,
    chipLoadMax: 0.005,
    feedRateMin: 180,
    feedRateMax: 180,
    feedRateStr: "180",
    rampDown: 90,
    depthPerPass: 0.125,
    depthPerPassStr: "1/8\" (0.125) — Not Recommended",
    depthPerPassNotRecommended: true,
    url: "https://www.amanatool.com/46202-k-sc-spektra-spiral-plunge-1-4-dia-x-3-4-x-1-4-inch-shank-down-cut.html"
  },
  {
    id: "amana-46282-k",
    name: "Amana 46282-K",
    partNumber: "46282-K",
    flutes: 4,
    direction: "Up-Cut Spiral",
    type: "2D/3D Carving Tapered Ball Tip",
    diameter: 0.0625,
    diameterStr: "1/16\"",
    angle: 5.4,
    radius: 0.03125,
    cuttingHeight: 1.0,
    shank: 0.25,
    overallLength: 3.0,
    chipLoadMin: 0.0005,
    chipLoadMax: 0.00065,
    feedRateMin: 35,
    feedRateMax: 45,
    feedRateStr: "35–45",
    rampDown: null,
    depthPerPass: null,
    depthPerPassStr: "",
    url: "https://www.amanatool.com/46282-k-cnc-2d-and-3d-carving-5-4-deg-tapered-angle-ball-tip-1-16-dia-x-1-32-radius-x-1-x-1-4-shank-x-3-inch-long-x-4-flute-solid-carbide-up-cut-spiral-spektratm-extreme-tool-life-coated-router-bit.html"
  },
  {
    id: "amana-45771-k",
    name: "Amana 45771-K",
    partNumber: "45771-K",
    flutes: null,
    direction: "",
    type: "30° Engraving",
    diameter: 0.005,
    diameterStr: "0.005\"",
    angle: 30,
    radius: null,
    cuttingHeight: 0.44,
    shank: 0.25,
    overallLength: 2.25,
    chipLoadMin: 0.003,
    chipLoadMax: 0.007,
    feedRateMin: 50,
    feedRateMax: 125,
    feedRateStr: "50–125",
    rampDown: null,
    depthPerPass: null,
    depthPerPassStr: "",
    url: "https://www.amanatool.com/45771-k-solid-carbide-30-degree-engraving-0-005-tip-width-x-1-4-inch-shank-signmaking-spektratm-extreme-tool-life-coated-router-bit.html"
  },
  {
    id: "amana-51766",
    name: "Amana 51766",
    partNumber: "51766",
    flutes: 2,
    direction: "Up-Cut Spiral",
    type: "Solid Carbide O-Flute Plastic Cutting",
    diameter: 0.125,
    diameterStr: "1/8\"",
    angle: null,
    radius: null,
    cuttingHeight: 0.75,
    shank: 0.25,
    overallLength: 2.5,
    chipLoadMin: null,
    chipLoadMax: null,
    feedRateMin: 70,
    feedRateMax: 110,
    feedRateStr: "70–110",
    rampDown: null,
    depthPerPass: 0.006,
    depthPerPassStr: "0.004\"–0.006\"",
    url: "https://www.amanatool.com/51766-solid-carbide-cnc-spiral-double-o-flute-plastic-cutting-1-8-dia-x-3-4-x-1-4-shank-x-2-1-2-inch-long-up-cut-router-bit.html"
  },
  {
    id: "amana-45624-k",
    name: "Amana 45624-K",
    partNumber: "45624-K",
    flutes: 3,
    direction: "",
    type: "60° V-Groove",
    diameter: 0.25,
    diameterStr: "1/4\"",
    angle: 60,
    radius: null,
    cuttingHeight: 0.21875,
    shank: 0.25,
    overallLength: 2.0,
    chipLoadMin: 0.0024,
    chipLoadMax: 0.0024,
    feedRateMin: 90,
    feedRateMax: 90,
    feedRateStr: "90",
    rampDown: null,
    depthPerPass: null,
    depthPerPassStr: "",
    url: "https://www.amanatool.com/45624-k-2.html"
  },
  {
    id: "amana-45704",
    name: "Amana 45704",
    partNumber: "45704",
    flutes: 2,
    direction: "",
    type: "90° V-Groove Carbide Tipped",
    diameter: 0.5,
    diameterStr: "1/2\"",
    angle: 90,
    radius: null,
    cuttingHeight: 0.25,
    shank: 0.25,
    overallLength: 1.625,
    chipLoadMin: null,
    chipLoadMax: null,
    feedRateMin: 90,
    feedRateMax: 90,
    feedRateStr: "90",
    rampDown: null,
    depthPerPass: 0.0024,
    depthPerPassStr: "0.0024\"",
    url: "https://www.amanatool.com/45704-carbide-tipped-v-groove-90-deg-x-1-2-dia-x-1-4-x-1-4-inch-shank.html"
  },
  {
    id: "amana-45982",
    name: "Amana 45982",
    partNumber: "45982",
    flutes: 2,
    direction: "",
    type: "Bowl/Tray (Radius)",
    diameter: 0.75,
    diameterStr: "3/4\"",
    angle: null,
    radius: 0.25,
    cuttingHeight: 0.625,
    shank: 0.25,
    overallLength: 2.40625,
    chipLoadMin: 0.0023,
    chipLoadMax: 0.0023,
    feedRateMin: 80,
    feedRateMax: 80,
    feedRateStr: "80",
    rampDown: 5,
    depthPerPass: 0.019685,
    depthPerPassStr: "0.019685\" / 0.5mm",
    url: "https://www.amanatool.com/45982-carbide-tipped-bowl-tray-1-4-radius-x-3-4-dia-x-5-8-x-1-4-inch-shank.html"
  },
  {
    id: "spetool-w04022",
    name: "SpeTool W04022",
    partNumber: "W04022",
    flutes: 2,
    direction: "Up",
    type: "Spiral Up-Cut Extra Long",
    diameter: 0.25,
    diameterStr: "1/4\"",
    angle: null,
    radius: null,
    cuttingHeight: 2.0,
    shank: 0.25,
    overallLength: 4.0,
    chipLoadMin: 0.005,
    chipLoadMax: 0.005,
    feedRateMin: 180,
    feedRateMax: 180,
    feedRateStr: "180",
    rampDown: 90,
    depthPerPass: null,
    depthPerPassStr: "",
    url: "https://spetools.com/products/spetool-w04022-spiral-up-cut-router-bit-1-4-dia-1-4-shank-4-extra-long"
  },
  {
    id: "idc-ball-nose-downcut",
    name: "IDC 1/4 Down-Cut Ball Nose Endmill",
    partNumber: "IDC-BN-DC-1-4",
    flutes: 2,
    direction: "Down",
    type: "Ball Nose Down-Cut",
    diameter: 0.25,
    diameterStr: "1/4\"",
    angle: null,
    radius: null,
    cuttingHeight: null,
    shank: 0.25,
    overallLength: 2.5,
    chipLoadMin: null,
    chipLoadMax: null,
    feedRateMin: 70,
    feedRateMax: 70,
    feedRateStr: "70",
    rampDown: null,
    depthPerPass: 0.12,
    depthPerPassStr: "0.120\"",
    url: "https://idcwoodcraft.com/products/1-4-ball-nose-downcut"
  },
  {
    id: "freud-04-096",
    name: "Freud 04-096",
    partNumber: "04-096",
    flutes: 2,
    direction: "",
    type: "Solid Carbide",
    diameter: 0.0625,
    diameterStr: "1/16\"",
    angle: null,
    radius: null,
    cuttingHeight: 0.25,
    shank: 0.25,
    overallLength: 1.625,
    chipLoadMin: 0.001008,
    chipLoadMax: 0.001008,
    feedRateMin: null,
    feedRateMax: null,
    feedRateStr: "",
    rampDown: null,
    depthPerPass: null,
    depthPerPassStr: "",
    url: "https://www.freudtools.com/products/04-096"
  },
  {
    id: "idc-the-beast",
    name: "IDC \"THE BEAST\"",
    partNumber: "IDC-BEAST",
    flutes: 3,
    direction: "",
    type: "Roughing Endmill",
    diameter: 0.25,
    diameterStr: "1/4\"",
    angle: null,
    radius: null,
    cuttingHeight: 0.25,
    shank: 0.25,
    overallLength: 2.5,
    chipLoadMin: null,
    chipLoadMax: null,
    feedRateMin: 100,
    feedRateMax: 100,
    feedRateStr: "100",
    rampDown: 80,
    depthPerPass: 0.75,
    depthPerPassStr: "0.750\"",
    url: "https://idcwoodcraft.com/products/the-beast-1-4-roughing-endmill-bit-for-cnc-routers-1-4-shank"
  }
];

// Spindle info — Makita RT0701C
const SPINDLE_INFO = {
  name: "Makita RT0701C (110v)",
  rpmMin: 10000,
  rpmMax: 30000,
  settings: [
    { setting: 1, rpm: 10000 },
    { setting: 2, rpm: 12000 },
    { setting: 3, rpm: 16000 },
    { setting: 4, rpm: 20000 },
    { setting: 5, rpm: 24000 },
    { setting: 6, rpm: 30000 }
  ],
  note: "We recommend staying between the first and second settings for most projects (10,000–12,000 RPM)."
};

// General rule: depth per pass should not exceed half the cutting diameter
const DEPTH_PER_PASS_RULE = "Depth per pass should not exceed half the cutting diameter of the bit.";

// Export for both browser and Node
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TOOL_DATABASE, SPINDLE_INFO, DEPTH_PER_PASS_RULE };
}